import type { Release } from '../../src/types/whats-new';

function toServedUrl(relPath: string): string {
  // relPath like "whats-new/1.0.11/close-pr.png" → "/whats-new/1.0.11/close-pr.png"
  return '/' + relPath.replace(/^\/+/, '');
}

function rewriteReleases(releases: Release[]): Release[] {
  return releases.map((r) => ({
    ...r,
    highlights: r.highlights.map((h) => ({
      ...h,
      hero: h.hero ? { src: toServedUrl(h.hero.src), alt: h.hero.alt } : null,
    })),
  }));
}

export function emitModule(releases: Release[]): string {
  const rewritten = rewriteReleases(releases);
  const body = JSON.stringify(rewritten, null, 2);
  return `// THIS FILE IS GENERATED by scripts/changelog/vite-plugin.ts.
// Edit /CHANGELOG.md and re-run \`npm run dev\` or \`npm run build\`.
import type { Release } from '@/types/whats-new';

export const RELEASES: Release[] = ${body};
`;
}
