// Sample PR data used across every surface so they feel like the same app.

const PRS = [
  {
    id: 715, number: 715, title: "AB#54258 / AB#54425 Portal. Quote: resolve Price Book list price on add",
    repo: "Gomocha-FSP/FSP", initials: "SS", avatarTone: "rose", own: false,
    status: "running", statusLabel: "7 running",
    score: 59, added: 135, deleted: 10, commits: 3, files: 1,
    branch: "features/54258-list-price-on-add-R5.2", target: "releases/R5.2",
    labels: ["AB#54258", "AB#54425", "AB#54729", "AB#54482"],
    checks: "3/8 passed",
    reviewState: null,
  },
  {
    id: 714, number: 714, title: "AB#54252 Portal. Quote grid: immediate delete, remove duplicate refresh",
    repo: "Gomocha-FSP/FSP", initials: "SS", avatarTone: "rose", own: false,
    status: "failing", statusLabel: "2 failing",
    score: 94, added: 97, deleted: 436, commits: 1, files: 9,
    branch: "features/54252-quote-grid-refresh-R5.2", target: "releases/R5.2",
    labels: ["AB#54252"],
    checks: "7/9 passed",
    reviewState: "approved",
  },
  {
    id: 713, number: 713, title: "AB#54482 Portal. Quote footer follow-ups: PricingAdjusted buttons, auto-save, modal layout",
    repo: "Gomocha-FSP/FSP", initials: "SS", avatarTone: "rose", own: false,
    status: "passing", statusLabel: "10 passed",
    score: 75, added: 130, deleted: 39, commits: 1, files: 6,
    branch: "features/54482-bugfixes-r2-R5.2", target: "releases/R5.2",
    labels: ["AB#54482"],
    checks: "10/10 passed",
    reviewState: null,
  },
  {
    id: 710, number: 710, title: "Portal. Allow overwriting widget-bound saved searches + Google Maps async",
    repo: "Gomocha-FSP/FSP", initials: "TV", avatarTone: "blue", own: false,
    status: "passing", statusLabel: "10 passed",
    score: 85, added: 99, deleted: 3, commits: 2, files: 5,
    branch: "fix/savedsearch-widget-overwrite-and-maps-async", target: "releases/R5.2",
    labels: [],
    checks: "10/10 passed",
    reviewState: "commented",
  },
  {
    id: 708, number: 708, title: "Add iOS CI workflow for Xcode 26 SDK build",
    repo: "Gomocha-FSP/FSP", initials: "SS", avatarTone: "rose", own: false,
    status: "passing", statusLabel: "1 passed",
    score: 70, added: 22, deleted: 0, commits: 1, files: 2,
    branch: "ci/ios-xcode-26", target: "main",
    labels: [],
    checks: "1/1 passed",
  },
  {
    id: 1398, number: 1398, title: "feat(ortec): Plan 9 — timeslot flow end-to-end (calculate + book)",
    repo: "Gomocha-FSP/fsp-horizon", initials: "KV", avatarTone: "rose", own: false,
    status: "failing", statusLabel: "1 failing",
    score: 74, added: 21277, deleted: 92, commits: 52, files: 109,
    branch: "feat/ortec-timeslot-flow-plan-9", target: "main",
    labels: [],
    checks: "27/28 passed",
  },
  {
    id: 1394, number: 1394, title: "feat(workspace-designer): Phase 2 — Layout tab",
    repo: "Gomocha-FSP/fsp-horizon", initials: "KV", avatarTone: "rose", own: true,
    status: "passing", statusLabel: "all clear",
    score: 50, added: 9210, deleted: 192, commits: 40, files: 52,
    branch: "feat/workspace-designer-phase2", target: "main",
    labels: [],
    draft: true,
    checks: "1/1 passed",
  },
  {
    id: 1384, number: 1384, title: "feat(workspace-designer): Phase 1 — foundation shell + read API + feature flag",
    repo: "Gomocha-FSP/fsp-horizon", initials: "KV", avatarTone: "rose", own: true,
    status: "passing", statusLabel: "passing",
    score: 60, added: 9897, deleted: 20, commits: 17, files: 66,
    branch: "feat/workspace-designer", target: "main",
    labels: [],
    draft: true,
    worktree: "worktree4",
    checks: "28/28 passed",
  },
  {
    id: 1362, number: 1362, title: "feat(planboard, orders): Zoom-to-order on map context-menu",
    repo: "Gomocha-FSP/fsp-horizon", initials: "TV", avatarTone: "blue", own: false,
    status: "passing", statusLabel: "passing",
    score: 50, added: 2375, deleted: 105, commits: 26, files: 71,
    branch: "fix/preview-fixes", target: "main",
    labels: ["AB#53457", "AB#53358"],
    draft: true,
    checks: "20/20 passed",
  },
];

Object.assign(window, { PRS });
