#!/usr/bin/env bun
// Keep the marketing site's design tokens identical to the app's.
//
//   bun scripts/site-tokens-check.ts          # fail on drift (runs first in `bun run site:build`)
//   bun scripts/site-tokens-check.ts --write  # regenerate site/src/styles/tokens.css from the app
//
// Sources (app):  src/BorgDock.Tauri/src/styles/index.css  top-level `:root` and `.dark`
//                 src/BorgDock.Tauri/src/styles/motion.css top-level `:root`
// Copy (site):    site/src/styles/tokens.css, which holds those blocks verbatim.
//
// Only top-level blocks count (a line that starts with `:root {` or `.dark {`);
// the reduced-motion overrides inside `@media` are the site's own business.
// Declarations are compared by name and whitespace-normalised value, so
// comments and formatting may differ; a missing, extra or changed declaration
// is drift.
//
// The check also fails when a colour literal (hex, rgb(), hsl()) appears
// anywhere in site/src outside tokens.css: every colour goes through a token.

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dir, '..');
const APP_INDEX = path.join(root, 'src/BorgDock.Tauri/src/styles/index.css');
const APP_MOTION = path.join(root, 'src/BorgDock.Tauri/src/styles/motion.css');
const SITE_TOKENS = path.join(root, 'site/src/styles/tokens.css');
const SITE_SRC = path.join(root, 'site/src');

type Selector = ':root' | '.dark';
interface Block {
  selector: Selector;
  text: string;
}

/** Top-level `:root { … }` / `.dark { … }` blocks, verbatim. */
function topLevelBlocks(css: string): Block[] {
  const blocks: Block[] = [];
  const re = /^(:root|\.dark)\s*\{/gm;
  let m: RegExpExecArray | null = re.exec(css);
  while (m) {
    let depth = 0;
    let i = m.index + m[0].length - 1;
    let inComment = false;
    for (; i < css.length; i++) {
      if (inComment) {
        if (css[i] === '*' && css[i + 1] === '/') {
          inComment = false;
          i++;
        }
        continue;
      }
      if (css[i] === '/' && css[i + 1] === '*') {
        inComment = true;
        i++;
        continue;
      }
      if (css[i] === '{') depth++;
      else if (css[i] === '}' && --depth === 0) break;
    }
    blocks.push({ selector: m[1] as Selector, text: css.slice(m.index, i + 1) });
    re.lastIndex = i + 1;
    m = re.exec(css);
  }
  return blocks;
}

/** name → normalised value for every declaration in the blocks of one selector. */
function declarations(blocks: Block[], selector: Selector): Map<string, string> {
  const out = new Map<string, string>();
  for (const b of blocks.filter((x) => x.selector === selector)) {
    const body = b.text
      .slice(b.text.indexOf('{') + 1, b.text.lastIndexOf('}'))
      .replace(/\/\*[\s\S]*?\*\//g, '');
    let depth = 0;
    let cur = '';
    const decls: string[] = [];
    for (const ch of body) {
      if (ch === '(') depth++;
      if (ch === ')') depth--;
      if (ch === ';' && depth === 0) {
        decls.push(cur);
        cur = '';
      } else cur += ch;
    }
    if (cur.trim()) decls.push(cur);
    for (const d of decls) {
      const idx = d.indexOf(':');
      if (idx < 0) continue;
      const name = d.slice(0, idx).trim();
      const value = d
        .slice(idx + 1)
        .replace(/\s+/g, ' ')
        .replace(/\(\s+/g, '(')
        .replace(/\s+\)/g, ')')
        .trim();
      if (name) out.set(name, value);
    }
  }
  return out;
}

function appBlocks(): { index: Block[]; motion: Block[] } {
  const index = topLevelBlocks(fs.readFileSync(APP_INDEX, 'utf8'));
  const motion = topLevelBlocks(fs.readFileSync(APP_MOTION, 'utf8')).filter(
    (b) => b.selector === ':root',
  );
  if (!index.some((b) => b.selector === ':root') || !index.some((b) => b.selector === '.dark')) {
    throw new Error(`could not find the top-level :root and .dark blocks in ${APP_INDEX}`);
  }
  return { index, motion };
}

function writeTokens(): void {
  const { index, motion } = appBlocks();
  const header = `/*
 * BorgDock design tokens, copied from the app so the site and the app are one
 * product. GENERATED by \`bun scripts/site-tokens-check.ts --write\` from
 *   src/BorgDock.Tauri/src/styles/index.css  (:root = Porcelain, .dark = Workbench graphite)
 *   src/BorgDock.Tauri/src/styles/motion.css (motion durations and easings)
 * Do not edit by hand: change the app, then rerun the command. \`bun run site:build\`
 * fails when this file and the app drift apart.
 */
`;
  const parts = [
    header.trimEnd(),
    ...index.map((b) => b.text),
    '/* Motion tokens (motion.css) */',
    ...motion.map((b) => b.text),
  ];
  fs.writeFileSync(SITE_TOKENS, `${parts.join('\n\n')}\n`);
  console.log(`site-tokens-check: wrote ${path.relative(root, SITE_TOKENS)}`);
}

function diff(): string[] {
  const { index, motion } = appBlocks();
  const app = [...index, ...motion];
  const site = topLevelBlocks(fs.readFileSync(SITE_TOKENS, 'utf8'));
  const problems: string[] = [];
  for (const sel of [':root', '.dark'] as const) {
    const a = declarations(app, sel);
    const s = declarations(site, sel);
    for (const [name, value] of a) {
      if (!s.has(name)) problems.push(`${sel} ${name}: missing on the site (app: ${value})`);
      else if (s.get(name) !== value)
        problems.push(`${sel} ${name}: site "${s.get(name)}" vs app "${value}"`);
    }
    for (const name of s.keys()) {
      if (!a.has(name)) problems.push(`${sel} ${name}: only on the site`);
    }
  }
  return problems;
}

function walk(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    return e.isDirectory() ? walk(p) : [p];
  });
}

/**
 * Colour literals in site/src outside tokens.css: hex (`#abc`, `#aabbcc`,
 * `#aabbccdd`) and `rgb(`/`rgba(`/`hsl(`/`hsla(`.
 */
function colourLiterals(): string[] {
  const hits: string[] = [];
  const hex = /(?<![\w&/])#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})(?![\w-])/g;
  const fn = /\b(?:rgba?|hsla?)\(/g;
  // `href="#add"`, `href={`#${id}`}` and `id="bad"` are anchors, not colours.
  const inAnchor = /(?:href|id)=\{?["'`][^"'`]*$/;
  for (const file of walk(SITE_SRC)) {
    if (path.resolve(file) === path.resolve(SITE_TOKENS)) continue;
    if (!/\.(astro|tsx?|jsx?|css|mjs)$/.test(file)) continue;
    const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
    lines.forEach((line, i) => {
      for (const m of line.matchAll(hex)) {
        // `#482` is a pull request number, not a colour: short forms only
        // count when they contain a letter.
        if (m[0].length <= 5 && !/[a-fA-F]/.test(m[0])) continue;
        if (inAnchor.test(line.slice(0, m.index))) continue;
        hits.push(`${path.relative(root, file)}:${i + 1}: ${m[0]}`);
      }
      for (const m of line.matchAll(fn)) {
        hits.push(`${path.relative(root, file)}:${i + 1}: ${m[0]}`);
      }
    });
  }
  return hits;
}

if (process.argv.includes('--write')) {
  writeTokens();
} else {
  const drift = diff();
  const hexes = colourLiterals();
  if (drift.length) {
    console.error(
      `site-tokens-check: site/src/styles/tokens.css has drifted from the app's tokens (${drift.length}):\n  ${drift.join('\n  ')}\n\nRun \`bun scripts/site-tokens-check.ts --write\` to copy the app's tokens to the site.`,
    );
  }
  if (hexes.length) {
    console.error(
      `site-tokens-check: colour literals outside tokens.css (use a token instead):\n  ${hexes.join('\n  ')}`,
    );
  }
  if (drift.length || hexes.length) process.exit(1);
  console.log('site-tokens-check: site tokens match the app');
}
